### ISSUE TITLE
Options or integration into the Sweetener.

### ISSUE THREAD

**Issue by BartKieviet** [BartKieviet/Bookkeeper#2]

**Comment by valitas** [comment]
We already have an options page, it was added in ac9336f6cbb528b6548740aeb13507cf3fc23caa (not that we have many "options" in it, but well, we have one).

I'm not sure what integration with Sweetener we could need. Maybe we could ask Sweetener to draw sector maps for us, showing the location of buildings? We should add specific issues for that or whatever we come up with. Closing this one because it really doesn't give us anything concrete to do.

**Comment by BartKieviet** [comment]
The idea was to integrate the whole app into the sweetener, you know, back when it was still small.
