### ISSUE TITLE
Fully stocked indicator own buildings

### ISSUE THREAD

**Issue by BartKieviet** [BartKieviet/Bookkeeper#41]
If min/maxes are unknown it does show ticks indicator (because we know that), but since we have no maxes it shows up as fully stocked.

**Comment by valitas** [comment]
Making a note so I don't forget: this happens when you have visited the overview, so your buildings were automatically tracked, but haven't yet visited the trade settings screen for them, so we don't know their maxes. It's fixed for the user after they visit trade settings at least once.

Noting this because I don't think it's likely we'll fix this before 2.1 is out, so we'll ship with this quirk...
